apiVersion: v1
kind: Service
metadata:
  name: membramoney-backend
  namespace: membramoney
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  type: ClusterIP
