[package]
name = "membramoney"
version = "0.1.0-devnet"
description = "Membra Money Protocol — Devnet-First Solana Program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "membramoney"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { version = "0.29.0", features = ["init-if-needed"] }
anchor-spl = "1.0.2"
# Pin solana-program to avoid borsh v1.6.1 -> borsh-derive -> proc-macro-crate -> toml_parser edition 2024 chain
solana-program = "=1.16.27"
